version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: search-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
  search_api:
    build: .
    container_name: search-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:

networks:
  default:
    name: share_network
    external: true